Temp changes

diff --git a/grm b/grm
--- a/grm
+++ b/grm
@@ -22,7 +22,7 @@ ErrorInvalidUsage="Ivalid usage, see \"man grm\" or \"grm help\""
 [ -f "$Config" ] && . "$Config"
 
 checkArgs() { # num of args, optional custom error msg
-	[ "$#" -ne "$1" ] && echo ${2-"$ErrorInvalidUsage"} > /dev/stderr && exit 1
+	[ "$1" -ne "$2" ] && echo ${3-"$ErrorInvalidUsage"} > /dev/stderr && exit 1
 	return 0
 }
 
@@ -37,11 +37,11 @@ updateCache(){
 }
 # Switch on command given as first argument
 case $1 in
-	pick) checkArgs 1
+	pick) checkArgs $# 1
 		# shellcheck disable=2086
 		updateCache && "$Dmenu" $DmenuFlags < "$CacheDirectory/repos" || exit 4
 		;;
-	clone) checkArgs 2 # grm clone <URL>
+	clone) checkArgs $# 2 # grm clone <URL>
 		# TODO Test for vaild url, instead of just missing
 		[ -z "$2" ] || echo "error: URL missing in \"grm clone <URL>, see \"man grm\" or \"grm help\"" \
 		> /dev/stderr && exit 1
@@ -60,7 +60,7 @@ case $1 in
 			exit 0
 		fi; exit 3
 		;;
-	delete) checkArgs 1
+	delete) checkArgs $# 1
 		# check if given args match else exit
 		[ "$#" -ne "1" ] && echo "$ErrorInvalidUsage" > /dev/stderr && exit 1
 		
@@ -75,7 +75,7 @@ case $1 in
 		done
 		updateCache
 		;;
-	configure) checkArgs 1
+	configure) checkArgs $# 1
 		# if config does'nt exist, create it with global defaults
 		if ! [ -f "$Config" ]; then writeConfig() {
 			echo "RepositoryDirectory=\"$RepositoryDirectory\""
@@ -91,11 +91,12 @@ case $1 in
 		$Editor "$Config" || exit 2
 		updateCache true
 		;;
-	query)		checkArgs 1 ; updateCache true ;;
-	version)	checkArgs 1 ; echo "grm v$($Version) - MIT License, Copyright (c) 2020 chemo-project" ;;
+	query)		checkArgs $# 1 ; updateCache true ;;
+	version)	checkArgs $# 1 ; echo "grm v$($Version) - MIT License, Copyright (c) 2020 chemo-project" ;;
 	help)
 		# print help/usage
 	;;
-	*) checkargs -1 # allways trigger, invalid usage
+	*)
+		checkArgs $# -1 # allways trigger, invalid usage
 esac
 exit 0
